version: '3.8'

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  frontend:
    image: raikhert/foodgramfront:latest
    volumes:
      - frontend_data:/app/result_build/
    depends_on:
      - db
  backend:
    image: setter2000/foodgram
    restart: always
    volumes:
      - # Контейнер web будет работать с данными, хранящиеся в томе static_value,
      # через свою директорию /code/static/
      - static_value:/code/static/

      # Данные, хранящиеся в томе media_value, будут доступны в контейнере web
      # через директорию /code/media/
      - media_value:/code/media/
    env_file:
      - ./.env
  migrations:
    image: raikhert/foodgramback:latest
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py createadmin &&
             python manage.py filldb"
    depends_on:
      - backend
    env_file:
      - ./.envs/.postgres
      - ./.envs/.django
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_data:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/foodgram/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/foodgram/docs/openapi-schema.yml
      - static_value:/code/static/
      - media_value:/code/media
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  frontend_data:
  static_value:
  media_value: