version: '3.8'

services:
  postgres:
    image: postgres:13.3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres

  frontend:
    image: raikhert/foodgramfront:latest
    volumes:
      - ./frontend/:/api/result_build/
    depends_on:
      - postgres

  backend:
    image: setter2000/foodgramback:latest
#    build:
#      dockerfile: ./backend/Dockerfile
#      context: .
    restart: always
    volumes:
      - static_value:/code/backend/static/
      - media_value:/code/backend/media/
    env_file:
      - ./.envs/.postgres
      - ./.envs/.django
    depends_on:
      - postgres

  migrations:
#    image: foodgram-project-react_backend
    image: setter2000/foodgramback:latest
    volumes:
      - .:/backend/
    command: bash -c "python manage.py makemigrations users --noinput &&
             python manage.py migrate --noinput &&
             python manage.py loaddata data/tag.json &&
             python manage.py loaddata data/ingredient.json &&
             python manage.py loaddata data/user.json"
    env_file:
      - ./.envs/.postgres
      - ./.envs/.django
    depends_on:
      - postgres

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
  result_build: