version: '3.8'

services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_data:/app/result_build/
    depends_on:
      - postgres
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    expose:
      - 8000
    restart: always
    volumes:
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/
    env_file:
      - ./.envs/.postgres
      - ./.envs/.django
  migrations:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py createadmin &&
             python manage.py filldb"
    depends_on:
      - backend
    env_file:
      - ./.envs/.postgres
      - ./.envs/.django
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./develop.conf:/etc/nginx/conf.d/default.conf
      - ../docs/redoc.html:/usr/share/nginx/html/foodgram/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/foodgram/docs/openapi-schema.yml
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/
      - ../frontend/build:/usr/share/nginx/html/
    depends_on:
      - postgres
      - backend
      - frontend

volumes:
  postgres_data:
  frontend_data:
  static_value:
  media_value:
