# Generated by Django 3.0.5 on 2021-10-06 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211005_1943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
