# Generated by Django 3.0.5 on 2021-10-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211003_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients_recipe', through='app.IngredientRecipes', to='app.Ingredient'),
        ),
    ]
