# Generated by Django 3.0.5 on 2021-10-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211011_1240'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipesingredients',
            unique_together={('ingredient', 'recipe', 'amount')},
        ),
    ]
