# Generated by Django 3.0.5 on 2021-10-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211008_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesingredients',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
