# Generated by Django 3.0.5 on 2021-10-05 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20211004_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(max_length=20000000, upload_to='recipes/images'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='is_favorited',
            field=models.ManyToManyField(help_text='Представлены, логины пользователей, кто добавил этот рецепт себе в избранное.', related_name='favorite_recipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(help_text='Теги для добавления к рецептам.', related_name='tag_recipe', to='app.Tag'),
        ),
    ]
