# Generated by Django 3.0.5 on 2021-10-05 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20211005_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='recipes/images'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='is_favorited',
            field=models.ManyToManyField(help_text='Представлен, лоигны пользователей, кто добавил этот рецепт себе в избранное.', related_name='favorite_recipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='app.Tag'),
        ),
    ]
