# Generated by Django 3.0.5 on 2021-10-01 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211001_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientofrecipes',
            name='amount',
        ),
        migrations.AlterField(
            model_name='ingredientofrecipes',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(through='app.IngredientOfRecipes', to='app.Ingredient'),
        ),
    ]
