# Generated by Django 3.0.5 on 2021-10-07 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20211006_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='is_favorited',
            field=models.ManyToManyField(blank=True, help_text='Представлен, лоигны пользователей, кто добавил этот рецепт себе в избранное.', related_name='favorite_recipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='is_in_shopping_cart',
            field=models.ManyToManyField(blank=True, help_text='Показывать только рецепты, находящиеся в списке покупок.', related_name='shopping_recipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
