# Generated by Django 3.0.5 on 2021-10-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211001_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Ингредиент'),
        ),
    ]
