# Generated by Django 3.0.5 on 2021-10-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211001_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default=1, max_length=150, verbose_name='Ингредиент'),
            preserve_default=False,
        ),
    ]
