# Generated by Django 3.0.5 on 2021-10-01 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211001_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientofrecipes',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ingredient', verbose_name='Ингредиент'),
        ),
    ]
